version: "3.8"

services:
  
  skin-sight-test:
    build:
      
      context: .
      target: test
    
    volumes:
      - type: bind
        source: ./
        target: /app
      - /app/node_modules
    
    env_file: .env
    
    command: npm run test
    
    ports:
      - "5000:5000"