apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
type: Opaque
data:
  SUPABASE_JWT_SECRET: b01jeE4vSTN1dzBBMWlVQnBHRTBwSGJTQWo1RGZvSzVFQ3I5UkRPSkxHQlQrVEkrenVubW14T2I4S0VnWDI1RGNRYTgxVmRtMXV4Y3djdXdCazFJMXc9PQ==
  SUPABASE_API_URL: aHR0cHM6Ly9rYmFtdHdpamd0YnB5ZHF1emNuZC5zdXBhYmFzZS5jby8=
  SUPABASE_ANON_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW10aVlXMTBkMmxxWjNSaWNIbGtjWFY2WTI1a0lpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTURjME56UTRORFVzSW1WNGNDSTZNakF5TXpBMU1EZzBOWDAuMV81TVZDWjhxZ18yZmN1U3V3SlRlaGgtbDZmdDNTYjhUQktwSGgzWDFJOA==
# stringData:
#   SUPABASE_JWT_SECRET: 'oMcxN/I3uw0A1iUBpGE0pHbSAj5DfoK5ECr9RDOJLGBT+TI+zunmmxOb8KEgX25DcQa81Vdm1uxcwcuwBk1I1w=='
#   SUPABASE_API_URL: 'https://kbamtwijgtbpydquzcnd.supabase.co/'
#   SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiYW10d2lqZ3RicHlkcXV6Y25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDc0NzQ4NDUsImV4cCI6MjAyMzA1MDg0NX0.1_5MVCZ8qg_2fcuSuwJTehh-l6ft3Sb8TBKpHh3X1I8'

# Secrets files need to be applied 
# kubectl apply -f skin-sight-backend-secrets.yml