apiVersion: v1
kind: Service
metadata:
  name: skin-sight-backend-service
spec:
  type: NodePort
  selector:
    # expose the pod with this label to the outside world (review the deployment file)
    app: skin-sight-backend
  ports:
    - name: skin-sight-backend # name of the service
      protocol: TCP
      port: 5000 # port of the NodePort Service
      targetPort: 5000 # port of the express app in the pod

# kubectl apply -f skin-sight-backend-service.yml