apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
type: Opaque
data:
  SUPABASE_JWT_SECRET: b01jeE4vSTN1dzBBMWlVQnBHRTBwSGJTQWo1RGZvSzVFQ3I5UkRPSkxHQlQrVEkrenVubW14T2I4S0VnWDI1RGNRYTgxVmRtMXV4Y3djdXdCazFJMXc9PQ==
  SUPABASE_API_URL: aHR0cHM6Ly9rYmFtdHdpamd0YnB5ZHF1emNuZC5zdXBhYmFzZS5jby8=
  SUPABASE_ANON_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW10aVlXMTBkMmxxWjNSaWNIbGtjWFY2WTI1a0lpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTURjME56UTRORFVzSW1WNGNDSTZNakF5TXpBMU1EZzBOWDAuMV81TVZDWjhxZ18yZmN1U3V3SlRlaGgtbDZmdDNTYjhUQktwSGgzWDFJOA==